// SPDX-License-Identifier: Apache-2.0

package main

var (
	sitesAvailableDir = "/etc/nginx/sites-available"
	sitesEnabledDir   = "/etc/nginx/sites-enabled"
	confdDir          = "/etc/nginx/conf.d"
	nginxConfRoot     = "/etc/nginx/nginx.conf"
)

const (
	suctlSuspendedWebroot   = "/var/www/suctl/suspended"
	suctlMaintenanceWebroot = "/var/www/suctl/maintenance"
)

const serverBlockTemplate = `# managed by suctl — do not edit this file directly
server {
    listen 80;
    server_name %s;
}
`

// suspendedBlockHTTPS: args = server_name, server_name, domain(cert), domain(cert)
const suspendedBlockHTTPS = `# managed by suctl — suspension override (HTTPS)
server {
    listen 80;
    server_name %s;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name %s;
    ssl_certificate     /etc/letsencrypt/live/%s/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/%s/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    root  /var/www/suctl/suspended;
    index index.html;
    location / { try_files $uri /index.html =403; }
}
`

const suspendedBlockHTTP = `# managed by suctl — suspension override (HTTP)
server {
    listen 80;
    server_name %s;
    root  /var/www/suctl/suspended;
    index index.html;
    location / { try_files $uri /index.html =403; }
}
`

// maintenanceBlockHTTPS: args = server_name, server_name, domain(cert), domain(cert)
const maintenanceBlockHTTPS = `# managed by suctl — maintenance override (HTTPS)
server {
    listen 80;
    server_name %s;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name %s;
    ssl_certificate     /etc/letsencrypt/live/%s/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/%s/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    root  /var/www/suctl/maintenance;
    index index.html;
    location / { try_files $uri /index.html =503; }
}
`

const maintenanceBlockHTTP = `# managed by suctl — maintenance override (HTTP)
server {
    listen 80;
    server_name %s;
    root  /var/www/suctl/maintenance;
    index index.html;
    location / { try_files $uri /index.html =503; }
}
`
